import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Header} from "@/components/header";

const myFont = localFont({
  src: [
    {
      path: "./fonts/SFPRODISPLAYREGULAR.woff",
      weight: '400',
      style: 'normal',
    },
    {
      path: "./fonts/SFPRODISPLAYMEDIUM.woff",
      weight: '500',
      style: 'italic',
    },
    {
      path: "./fonts/SFPRODISPLAYBOLD.woff",
      weight: '700',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
          className={myFont.className}
      >
      <div className="flex flex-col text-black bg-white">
          <Header/>
        {children}
      </div>
      </body>
      </html>
  );
}
